### Create New Category
POST http://localhost:8080/api/categories HTTP/1.1
Authorization: Bearer AOM03FS90G7HgW0A0Ze0Dw==
content-length: 21
content-type: application/json

{
    "name": "Machine"
}

### GET All Category
GET http://localhost:8080/api/categories HTTP/1.1
content-length: 21
content-type: application/json

### GET All Category With it's Words
GET http://localhost:8080/api/categories/withWords HTTP/1.1
content-length: 21
content-type: application/json

### POST Add Catagory(Health) to Word(2D3D9CC6-CD10-4A9F-A4B8-E2113E179E3D)
POST http://localhost:8080/api/words/2D3D9CC6-CD10-4A9F-A4B8-E2113E179E3D/categories/07ED5600-CC8D-4857-8E65-9981B920EC85
content-length: 21
content-type: application/json
Authorization: Bearer AOM03FS90G7HgW0A0Ze0Dw==

### GET Category(Technology)s WORDS
GET http://localhost:8080/api/categories/F7BDF43F-E5FC-4C6F-B156-1178B3837AEC/words


### GET Category(Finance)s WORDS
GET http://localhost:8080/api/categories/396C39C6-1A7E-4984-8C33-89C98CD10ED6/words


### Remove Relationship
DELETE http://localhost:8080/api/words/2D3D9CC6-CD10-4A9F-A4B8-E2113E179E3D/categories/07ED5600-CC8D-4857-8E65-9981B920EC85
Authorization: Bearer AOM03FS90G7HgW0A0Ze0Dw==


### 
GET https://wordsapiv1.p.rapidapi.com/words/frequently
X-RapidAPI-Key: 767e46fc15msha947d9612078375p1eb21fjsn401280b9bb27
X-RapidAPI-Host: wordsapiv1.p.rapidapi.com



{
  "type": "object",
  "properties": {
    "word": {
      "type": "string"
    },
    "results": {
      "type": "array",
      "items": {
        "type": "object"
      }
    },
    "syllables": {
      "type": "object",
      "properties": {
        "count": {
          "type": "integer"
        },
        "list": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "pronunciation": {
      "type": "object",
      "properties": {
        "all": {
          "type": "string"
        }
      }
    }
  }
}