### LOGIN
POST http://localhost:8080/api/users/login
Authorization: Basic kanein:password


### LOGIN
POST http://localhost:8080/api/users/login
Authorization: Basic admin:password


### CREATE NEW USER
POST http://localhost:8080/api/users HTTP/1.1
content-length: 21
content-type: application/json

{
    "name": "kane",
    "username": "kanein12",
    "password": "password"
}

### GET ALL USERS
GET http://localhost:8080/api/users HTTP/1.1
content-length: 21
content-type: application/json