POST http://localhost:8080/api/words HTTP/1.1
content-length: 21
content-type: application/json

{
    "name": "abc",
    "meaning": "123"
}

### GET ALL
GET http://localhost:8080/api/words HTTP/1.1
content-length: 21
content-type: application/json

### GET - SEARCH
GET http://localhost:8080/api/words/5F31152E-7F3C-420E-A840-B41B3F8CBB59 HTTP/1.1
content-length: 21
content-type: application/json

###

PUT http://localhost:8080/api/words/5F31152E-7F3C-420E-A840-B41B3F8CBB59 HTTP/1.1
content-length: 21
content-type: application/json

{
    "name": "Milky Way",
    "meaning": "gggadwad"
}

### DELETE

DELETE http://localhost:8080/api/words/5F31152E-7F3C-420E-A840-B41B3F8CBB59 HTTP/1.1
content-length: 21
content-type: application/json

{
    "name": "Milky Way",
    "meaning": "absdad31313131"
}

###
GET http://localhost:8080/api/words/search?term=Milky%20Way
content-length: 21
content-type: application/json

###
GET http://localhost:8080/api/words/search?term=absdad
content-length: 21
content-type: application/json

### FIRST

GET http://localhost:8080/api/words/first
content-length: 21
content-type: application/json

### SORT
GET http://localhost:8080/api/words/sorted
content-length: 21
content-type: application/json
