POST http://localhost:8080/api/words HTTP/1.1
content-length: 21
content-type: application/json

{
    "name": "Milky Way",
    "meaning": "absdad"
}

### GET ALL
GET http://localhost:8080/api/words HTTP/1.1
content-length: 21
content-type: application/json

### GET - SEARCH
GET http://localhost:8080/api/words/5F31152E-7F3C-420E-A840-B41B3F8CBB59 HTTP/1.1
content-length: 21
content-type: application/json

###

PUT http://localhost:8080/api/words/191045C9-824C-445C-A3B0-5B3CABA277CB HTTP/1.1
content-length: 21
content-type: application/json

{
    "name": "Milky Way",
    "meaning": "absdad31313131"
}

### DELETE

DELETE http://localhost:8080/api/words/191045C9-824C-445C-A3B0-5B3CABA277CB HTTP/1.1
content-length: 21
content-type: application/json

{
    "name": "Milky Way",
    "meaning": "absdad31313131"
}

###
GET http://localhost:8080/api/words/search?term=Milky%20Way
content-length: 21
content-type: application/json

###
GET http://localhost:8080/api/words/search?term=absdad
content-length: 21
content-type: application/json

